apiVersion: v1
kind: Service
metadata:
  name: amule-service
  labels:
    app: amule
spec:
  selector:
    app: amule
  type: NodePort
  ports:
  - name: gui
    protocol: TCP 
    port: 4711
  - name: web
    protocol: TCP 
    port: 4712
  - name: emule-tcp
    protocol: TCP 
    port: 4662
  - name: emule-udp
    protocol: UDP
    port: 4672
